receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      memory:
      disk:
      network:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector-metrics"
          scrape_interval: 60s
          static_configs:
            - targets: ["0.0.0.0:8888"]

exporters:
  # Add exporter for Better Stack:
  otlphttp/betterstack:
    endpoint: "https://s1559728.eu-nbg-2.betterstackdata.com"
    headers:
      Authorization: "Bearer p7vbXGbURyU8dfuqcKbnDu6o"

processors:
  batch:

service:
  pipelines:
    # Add extra logs and metrics pipelines for Better Stack:
    metrics/betterstack:
      receivers: [hostmetrics, otlp, prometheus] # your metrics receivers
      processors: [batch]
      exporters: [otlphttp/betterstack]
    logs/betterstack:
      receivers: [otlp] # your logs receivers
      processors: [batch]
      exporters: [otlphttp/betterstack]
    traces/betterstack:
      receivers: [otlp] # your traces receivers
      processors: [batch]
      exporters: [otlphttp/betterstack]
